FROM openjdk:8

RUN apt-get update && apt-get install -y maven
COPY . /project
RUN  cd /project && mvn clean package
EXPOSE 8075 5005

#ENTRYPOINT [this part for debug is moved into compose file, into "command"]


