version: "3.9"
networks:
  test:
volumes:
  db_data: { }

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ordo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - test

  app:
    build:
      context: .
      dockerfile: Dockerfile-debug
    ports:
      - "8075:8075"
      - "5005:5005"
    networks:
      - test
    depends_on:
      - db
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005 -jar orgo-0.0.1-SNAPSHOT.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user:password@db:3306/ordo?reconnect=true&&allowPublicKeyRetrieval=true&&useSSL=false
      SPRING_PROFILES_ACTIVE: local
      PORT: 8075